version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    links:
      - bancodedados
  bancodedados:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: arquiveidb
      MYSQL_USER: arquivei
      MYSQL_PASSWORD: 123Arquivei
      MYSQL_ROOT_PASSWORD: 123
  phpqa:
    image: jakzal/phpqa:php7.1-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - "bancodedados:db"

